site_name: EffectPlayer Docs

repo_url: https://github.com/TheRealVira/EffectPlayer

theme:
  name: "material"

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        load_external_modules: true
